spring:
  application:
    name: product-service
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:productDB;DB_CLOSE_DELAY=1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

server:
  port: 8081
  servlet:
    context-path: /products

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm::ss} {LOG_LEVEL_PATTERN:-%5p} %m%n"

eureka:
  client:
    service-url:
      "default-zone": http://localhost:8099/eureka/